apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ryanj2-poi-backend-app-dev
  annotations:
    argocd/app-name: ryanj2-poi-backend-app-dev
    backstage.io/kubernetes-id: ryanj2-poi-backend-app-dev
    backstage.io/kubernetes-namespace: ryanj2
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=ryanj2-poi-backend-app-dev'
    backstage.io/techdocs-ref: dir:.
    janus-idp.io/tekton-enabled : 'false'
    github.com/project-slug: Summit23Janus1/ryanj2-backend
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/ryanj2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/ryanj2/deployments/poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/ryanj2-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-ryanj2
  providesApis:
    - backend-api-ryanj2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ryanj2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-ryanj2
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://poi-backend-app-ryanj2.apps.summit23rock.n26o.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23Janus1/ryanj2-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-ryanj2
  definition:
    $text: https://github.com/Summit23Janus1/ryanj2-backend/tree/main/src/main/resources/META-INF/openapi.yaml
